apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-dedup
  labels:
    name: parsec-dedup
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_dedup
        name: parsec-dedup
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: 
          - "-c"
          - "taskset -c "${DEDUP_CORES}" ./run -a run -S parsec -p dedup -i native -n "$DEDUP_THREADS""
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "${DEDUP_NODE}"
