apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-canneal
  labels:
    name: parsec-canneal
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_canneal
        name: parsec-canneal
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: 
          - "-c"
          - "taskset -c ${CANNEAL_CORES} ./run -a run -S parsec -p canneal -i native -n ${CANNEAL_THREADS}"
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "${CANNEAL_NODE}"
