apiVersion: v1
kind: Pod
metadata:
  name: some-memcached
  labels:
    name: some-memcached
spec:
  containers:
    - image: anakli/memcached:t1
      name: memcached
      imagePullPolicy: Always
      command: ["/bin/sh"]
      args:
        - "-c"
        - "taskset -c ${MEMCACHED_CORES} ./memcached -t ${MEMCACHED_THREADS} -u memcache"
  nodeSelector:
    cca-project-nodetype: "${MEMCACHED_NODE}"



