apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-freqmine
  labels:
    name: parsec-freqmine
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_freqmine
        name: parsec-freqmine
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: 
          - "-c"
          - "taskset -c ${FREQMINE_CORES} ./run -a run -S parsec -p freqmine -i native -n ${FREQMINE_THREADS}"
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "${FREQMINE_NODE}"
